=== virtualidentityag/caritas-rework-onlineBeratung-consultingTypeService/src/main/resources/schemas/consulting-type.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://onlineberatung/consultingtype",
  "definitions": {
    "Component": {
      "type": "object",
      "properties": {
        "headline": {
          "description": "Human readable label that will be printed along the component.",
          "type": "string"
        },
        "name": {
          "description": "Identifier for the component.",
          "type": "string"
        }
      },
      "requires": [
        "headline",
        "description"
      ]
    },
    "RadioButton": {
      "type": "object",
      "description": "A group of values where only one can be selected.",
      "properties": {
        "componentType": {
          "description": "Identifier for the component.",
          "type": "string",
          "const": "RadioButton"
        },
        "radioButtons": {
          "description": "Individual values that can be selected.",
          "type": "array",
          "items": {
            "inputId": {
              "description": "Identifier for the value.",
              "type": "string"
            },
            "label": {
              "description": "Human readable label.",
              "type": "string"
            },
            "checked": {
              "description": "If true, this value will be selected by default.",
              "checked": "boolean"
            }
          },
          "required": [
            "inputId",
            "label",
            "checked"
          ]
        }
      },
      "extends": {
        "type": "object",
        "javaType": "de.caritas.cob.consultingtypeservice.schemas.model.Component"
      },
      "required": [
        "componentType",
        "radioButtons"
      ]
    },
    "TagSelect": {
      "description": "A group of values where multiple can be selected.",
      "type": "object",
      "properties": {
        "componentType": {
          "description": "Identifier for the component.",
          "type": "string",
          "const": "TagSelect"
        },
        "tagSelects": {
          "description": "Individual values that can be selected.",
          "type": "array",
          "items": {
            "id": {
              "description": "Identifier of the value.",
              "type": "string"
            },
            "label": {
              "description": "Human readable label.",
              "type": "string"
            }
          },
          "required": [
            "value",
            "label"
          ]
        }
      },
      "extends": "#/definitions/Component",
      "required": [
        "componentType",
        "tagSelects"
      ]
    },
    "SelectDropdown": {
      "description": "A group of values where only one can be selected and is rendered at a time.",
      "type": "object",
      "properties": {
        "componentType": {
          "description": "Identifier for the component.",
          "type": "string",
          "const": "SelectDropdown"
        },
        "item": {
          "description": "An individual item that can be selected.",
          "type": "object",
          "properties": {
            "id": {
              "description": "Identifier of the component.",
              "type": "string"
            },
            "selectedOptions": {
              "description": "Individual values that can be selected.",
              "type": "array",
              "items": {
                "value": {
                  "description": "Identifier of the value.",
                  "type": "string"
                },
                "label": {
                  "description": "Human readable label.",
                  "type": "string"
                }
              },
              "required": [
                "value",
                "label"
              ]
            },
            "selectInputLabel": {
              "description": "Human readable label for the component.",
              "type": "string"
            },
            "useIconOption": {
              "description": "Can be enabled to show an icon beside individual options.",
              "type": "boolean"
            },
            "isSearchable": {
              "description": "Allow the user to search for options by their label.",
              "type": "boolean"
            },
            "menuPlacement": {
              "description": "Eiter 'top' or 'bottom' (default: 'bottom').",
              "type": "string"
            }
          },
          "required": [
            "id",
            "selectedOptions",
            "selectInputLabel",
            "useIconOption",
            "isSearchable",
            "menuPlacement"
          ]
        }
      },
      "extends": "#/definitions/Component",
      "required": [
        "componentType",
        "item"
      ]
    }
  },
  "title": "Consulting type",
  "description": "Settings for a consulting type",
  "type": "object",
  "properties": {
    "id": {
      "description": "The unique identifier for the consulting type",
      "type": "integer",
      "minimum": 0
    },
    "tenantId": {
      "description": "The unique identifier of the tenant that the consulting type belongs to.",
      "type": [
        "integer",
        "null"
      ],
      "minimum": 0,
      "default": null
    },
    "description": {
      "description": "Description for the consulting type",
      "type": "string",
      "default": null
    },
    "groups": {
      "description": "Group names - the same group names are combined in the consulting type structure",
      "type": "array",
      "items": {
          "type": "string",
          "minLength": 1
      }
    },
    "furtherInformation": {
      "description": "Label and link for further information of the consulting type",
      "type": "object",
      "default": null,
      "properties": {
        "label": {
          "description": "The label for the link",
          "type": "string"
        },
        "url": {
          "description": "The link",
          "type": "string"
        }
      },
      "required": [
        "label",
        "url"
      ]
    },
    "slug": {
      "description": "The unique slug for the consulting type",
      "type": "string"
    },
    "excludeNonMainConsultantsFromTeamSessions": {
      "description": "True, if only consultants with role main-consultant should be added to all team sessions",
      "type": "boolean",
      "default": false
    },
    "lockedAgencies": {
      "description": "If true, no agency with this consulting type can be deleted or set offline via the admin api",
      "type": "boolean",
      "default": false
    },
    "whiteSpot": {
      "description": "Behavior regarding the white spots agencies",
      "type": "object",
      "properties": {
        "whiteSpotAgencyAssigned": {
          "description": "If true, agency with id in property 'whiteSpotAgencyId' will be proposed if no agency was found via given postcode in registration form",
          "type": ["null","boolean"]
        },
        "whiteSpotAgencyId": {
          "description": "The id the of the white spot agency",
          "type": ["integer", "null"]
        }
      },
      "required": [
        "whiteSpotAgencyAssigned"
      ]
    },
    "groupChat": {
      "description": "Group chat settings",
      "type": "object",
      "properties": {
        "isGroupChat": {
          "description": "True, if group chats are provided for this consulting type",
          "type": "boolean",
          "default": false
        },
        "groupChatRules" : {
          "description": "Rules for the group chat which are displayed to the user",
          "type" : ["array", "null"],
          "items" : {
            "type" : "string"
          }
        }
      },
      "required": [
        "isGroupChat"
      ]
    },
    "consultantBoundedToConsultingType": {
      "description": "True, if a consultant may only be assigned to agencies with this consulting type",
      "type": "boolean",
      "default": false
    },
    "welcomeMessage": {
      "description": "Settings for the welcome message",
      "type": "object",
      "properties": {
        "sendWelcomeMessage": {
          "description": "Indicates whether if the system should send an automatic reply message to all enquiries for this consulting type or not",
          "type": "boolean",
          "default": false
        },
        "welcomeMessageText": {
          "description": "The welcome message text for this consulting type -> null, if sendWelcomeMessage is false",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "sendWelcomeMessage",
        "welcomeMessageText"
      ]
    },
    "sendFurtherStepsMessage": {
      "description": "Indicates whether if the system should send an automatic further steps message to all enquiries for this consulting type or not",
      "type": "boolean",
      "default": true
    },
    "sendSaveSessionDataMessage": {
      "description": "Indicates whether if the system should send an automatic message with a prompt for the user to enter optional information to the session",
      "type": "boolean",
      "default": true
    },
    "sessionDataInitializing": {
      "description": "Settings to control which optional fields for consultation should be initialized for this consultation type.",
      "type": "object",
      "properties": {
        "addictiveDrugs": {
          "description": "True, if the field addictiveDrugs should be initialized for this consulting type",
          "type": "boolean",
          "default": "false"
        },
        "age": {
          "description": "True, if the field age should be initialized for this consulting type",
          "type": "boolean",
          "default": "false"
        },
        "gender": {
          "description": "True, if the field gender should be initialized for this consulting type",
          "type": "boolean",
          "default": "false"
        },
        "relation": {
          "description": "True, if the field relation should be initialized for this consulting type",
          "type": "boolean",
          "default": "false"
        },
        "state": {
          "description": "True, if the field state should be initialized for this consulting type",
          "type": "boolean",
          "default": "false"
        }
      }
    },
    "initializeFeedbackChat": {
      "description": "Indicates whether the feedback chat should be initialized for every session of this consulting type",
      "type": "boolean",
      "default": false
    },
    "isPeerChat": {
      "description": "Indicates whether the chat should be initialized as peer chat for every session of this consulting type",
      "type": "boolean",
      "default": false
    },
    "languageFormal": {
      "description": "Indicates whether the feedback chat should be initialized for every session of this consulting type",
      "type": "boolean",
      "default": true
    },
    "roles": {
      "description": "Role definitions",
      "type": "object",
      "properties": {
        "consultant": {
          "description": "Role definitions for consultants",
          "type": "object",
          "additionalProperties": {
            "type": "array"
          },
          "javaType": "java.util.Map<String, java.util.List<String>>"
        }
      }
    },
    "notifications": {
      "description": "Settings for the mail notifications",
      "type": "object",
      "properties": {
        "teamSessions": {
          "description": "Special mail notification settings for team sessions",
          "type": "object",
          "properties": {
            "newMessage": {
              "description": "Special mail notification settings for new messages",
              "type": "object",
              "properties": {
                "allTeamConsultants": {
                  "description": "If true, all consultants will be informed by email",
                  "type": "boolean"
                }
              },
              "required": [
                "allTeamConsultants"
              ]
            }
          },
          "required": [
            "newMessage"
          ]
        }
      },
      "required": [
        "teamSessions"
      ]
    },
    "registration": {
      "description": "Settings for the registration process",
      "type": "object",
      "properties": {
        "minPostcodeSize": {
          "description": "The minimum number of digits for the postal code that must be entered during registration.",
          "type": "integer",
          "default": 5
        },
        "autoSelectAgency": {
          "description": "For consulting types to which only one agency is assigned: if true the assigned agency is automatically selected",
          "type": "boolean",
          "default": false
        },
        "autoSelectPostcode": {
          "description": "If true postcode is automatically taken over from agency in the registration form",
          "type": "boolean",
          "default": false
        },
        "notes": {
          "description": "Additional info to display in agency selection and password accordion (optional)",
          "type": "object",
          "properties": {
            "agencySelection": {
              "description": "Additional info to display in agency selection",
              "type": ["string", "null"],
              "default": null
            },
            "password": {
              "description": "Additional info to display in password accordion",
              "type": ["string", "null"],
              "default": null
            }
          }
        },
        "mandatoryFields": {
          "description": "Control of mandatory fields for registration",
          "type": "object",
          "properties": {
            "age": {
              "description": "If true, this field is mandatory for the registration",
              "type": "boolean"
            },
            "state": {
              "description": "If true, this field is mandatory for the registration",
              "type": "boolean"
            }
          },
          "required": [
            "age",
            "state"
          ]
        }
      },
      "required": [
        "mandatoryFields",
        "notes"
      ]
    },
    "urls": {
      "description": "Forwarding urls",
      "type": "object",
      "properties": {
        "requiredAidMissingRedirectUrl": {
          "description": "If no `aid` query parameter (agency ID) is passed to the respective registration page as get parameter, the UI will redirect to this URL.",
          "type": ["string", "null"],
          "default": null
        },
        "registrationPostcodeFallbackUrl": {
          "description": "If no white spot agency provided for this consulting type a note is display with a link to this url, in case no matching agency for the given postcode was found",
          "type": ["string", "null"],
          "default": null
        }
      }
    },
    "showAskerProfile": {
      "description": "True to show asker profile for consultants. False, when asker profile should not be viewable.",
      "type": "boolean",
      "default": true
    },
    "isVideoCallAllowed": {
      "description": "True to enable video call buttons for consultants. False, when video call should be deactivated for consulting type.",
      "type": "boolean",
      "default": false
    },
    "isSubsequentRegistrationAllowed": {
      "description": "If true, askers additionally can register for this consulting type on their profile page at a later date.",
      "type": "boolean",
      "default": true
    },
    "requiredComponents": {
      "description:": "Can be provided if additional data is required for registration.",
      "type": ["object", "null"],
      "properties": {
        "age": {
          "description": "Age of the asker.",
          "type": "object",
          "properties": {
            "isEnabled": {
              "description": "If this is true, the age selection will be displayed.",
              "type": "boolean",
              "default": true
            },
            "options": {
              "description": "Individual values that can be selected.",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "value": {
                    "description": "Identifier for the option.",
                    "type": "string"
                  },
                  "label": {
                    "description": "Human readable label for the option.",
                    "type": "string"
                  }
                },
                "required": [
                  "value",
                  "label"
                ]
              }
            }
          },
          "required": [
            "options",
            "isEnabled"
          ]
        },
        "state": {
          "description": "Selection for the federal state of the asker.",
          "type": "object",
          "properties": {
            "isEnabled": {
              "description": "If this is true, the state selection will be displayed.",
              "type": "boolean",
              "default": true
            }
          }
        }
      },
      "required": [
        "age",
        "state"
      ]
    }
  },
  "required": [
    "id",
    "slug",
    "roles",
    "registration",
    "urls"
  ]
}

=== virtualidentityag/caritas-rework-onlineBeratung-consultingTypeService/src/test/resources/consulting-type-settings/consulting-type-2.json
{
  "id": 2,
  "tenantId": null,
  "groups": [
    "group2"
  ],
  "furtherInformation": {
    "label": "Lorem Impsum",
    "url": "https://www.domain.com"
  },
  "slug": "consultingtype2",
  "consultantBoundedToConsultingType": false,
  "sendSaveSessionDataMessage": true,
  "isVideoCallAllowed": false,
  "languageFormal": true,
  "roles": {
    "consultant": {
      "defaultRole": [
        "consultant"
      ]
    }
  },
  "registration": {
    "mandatoryFields": {
      "age": false,
      "state": false
    },
    "notes": {
    }
  },
  "urls": {
  },
  "isSubsequentRegistrationAllowed": false
}

=== virtualidentityag/caritas-rework-onlineBeratung-consultingTypeService/src/test/resources/consulting-type-settings/consulting-type-1.json
{
  "id": 1,
  "tenantId": null,
  "groups": [
    "group2",
    "group3"
  ],
  "description": "Lorem ipsum",
  "slug": "consultingtype1",
  "consultantBoundedToConsultingType": false,
  "sendSaveSessionDataMessage": true,
  "isVideoCallAllowed": false,
  "languageFormal": true,
  "roles": {
    "consultant": {
      "defaultRole": [
        "consultant"
      ]
    }
  },
  "registration": {
    "mandatoryFields": {
      "age": false,
      "state": false
    },
    "notes": {

    }
  },
  "urls": {
  } ,
  "isSubsequentRegistrationAllowed": false
}

=== virtualidentityag/caritas-rework-onlineBeratung-consultingTypeService/src/test/resources/consulting-type-settings-tenant-specific/consulting-type-2.json
{
  "id": 12,
  "tenantId": 3,
  "groups": [
    "group3"
  ],
  "description": "Lorem ipsum",
  "slug": "consultingtype12",
  "consultantBoundedToConsultingType": false,
  "sendSaveSessionDataMessage": true,
  "isVideoCallAllowed": false,
  "languageFormal": true,
  "roles": {
    "consultant": {
      "defaultRole": [
        "consultant"
      ]
    }
  },
  "registration": {
    "mandatoryFields": {
      "age": false,
      "state": false
    },
    "notes": {

    }
  },
  "urls": {
  } ,
  "isSubsequentRegistrationAllowed": false
}

=== virtualidentityag/caritas-rework-onlineBeratung-consultingTypeService/src/test/resources/consulting-type-settings/consulting-type-3.json
{
  "id": 3,
  "tenantId": null,
  "slug": "consultingtype3",
  "consultantBoundedToConsultingType": false,
  "sendSaveSessionDataMessage": true,
  "isVideoCallAllowed": false,
  "languageFormal": true,
  "roles": {
    "consultant": {
      "defaultRole": [
        "consultant"
      ]
    }
  },
  "registration": {
    "mandatoryFields": {
      "age": false,
      "state": false
    },
    "notes": {

    }
  },
  "urls": {
  } ,
  "isSubsequentRegistrationAllowed": false
}

=== virtualidentityag/caritas-rework-onlineBeratung-consultingTypeService/src/test/resources/consulting-type-settings/consulting-type-0.json
{
  "id": 0,
  "tenantId": null,
  "groups": [
    "group1"
  ],
  "description": "Lorem ipsum",
  "furtherInformation": {
    "label": "Lorem Impsum",
    "url": "https://www.domain.com"
  },
  "slug": "consultingtype0",
  "excludeNonMainConsultantsFromTeamSessions": false,
  "consultantBoundedToConsultingType": false,
  "isSubsequentRegistrationAllowed": true,
  "showAskerProfile": false,
  "isVideoCallAllowed": false,
  "welcomeMessage": {
    "sendWelcomeMessage": true,
    "welcomeMessageText": "Lorem ipsum"
  },
  "sendFurtherStepsMessage": true,
  "sessionDataInitializing": {
    "addictiveDrugs": true,
    "age": true,
    "gender": true,
    "relation": true,
    "state": true
  },
  "whiteSpot": {
    "whiteSpotAgencyAssigned": true,
    "whiteSpotAgencyId": 100
  },
  "groupChat": {
    "isGroupChat": true,
    "groupChatRules": [
      "Lorem ipsum",
      "Lorem ipsum"
    ]
  },
  "languageFormal": true,
  "roles": {
    "consultant": {
      "main": [
        "consultant",
        "u25-consultant",
        "u25-main-consultant"
      ],
      "peer": [
        "consultant",
        "u25-consultant"
      ]
    }
  },
  "notifications": {
    "teamSessions": {
      "newMessage": {
        "allTeamConsultants": false
      }
    }
  },
  "registration": {
    "minPostcodeSize": 3,
    "autoSelectAgency": true,
    "autoSelectPostcode": true,
    "mandatoryFields": {
      "age": false,
      "state": false
    },
    "notes": {
      "agencySelection": "Lorem ipsum",
      "password": "Dolor sit amet"
    }
  },
  "urls": {
    "requiredAidMissingRedirectUrl": "https://www.domain.tld/requiredAidMissingRedirectPath",
    "registrationPostcodeFallbackUrl": "https://www.domain.tld/registrationPostcodeFallbackPath"
  },
  "requiredComponents": {
    "age": {
      "isEnabled": true,
      "options": [
        {
          "value": "50",
          "label": "20"
        },
        {
          "value": "51",
          "label": "21"
        },
        {
          "value": "52",
          "label": "22"
        },
        {
          "value": "53",
          "label": "23"
        },
        {
          "value": "54",
          "label": "24"
        },
        {
          "value": "55",
          "label": "25"
        },
        {
          "value": "56",
          "label": "26"
        }
      ]
    },
    "state": {
      "isEnabled": true
    }
  }
}

=== virtualidentityag/caritas-rework-onlineBeratung-consultingTypeService/src/test/resources/consulting-type-settings-tenant-specific/consulting-type-0.json
{
  "id": 10,
  "tenantId": 1,
  "groups": [
    "group1",
    "group2"
  ],
  "description": "Lorem ipsum",
  "furtherInformation": {
    "label": "Lorem Impsum",
    "url": "https://www.domain.com"
  },
  "slug": "consultingtype10",
  "consultantBoundedToConsultingType": false,
  "isSubsequentRegistrationAllowed": true,
  "showAskerProfile": false,
  "isVideoCallAllowed": false,
  "welcomeMessage": {
    "sendWelcomeMessage": true,
    "welcomeMessageText": "Lorem ipsum"
  },
  "sendFurtherStepsMessage": true,
  "sessionDataInitializing": {
    "addictiveDrugs": true,
    "age": true,
    "gender": true,
    "relation": true,
    "state": true
  },
  "whiteSpot": {
    "whiteSpotAgencyAssigned": true,
    "whiteSpotAgencyId": 100
  },
  "groupChat": {
    "isGroupChat": true,
    "groupChatRules": [
      "Lorem ipsum",
      "Lorem ipsum"
    ]
  },
  "initializeFeedbackChat": false,
  "isPeerChat": false,
  "languageFormal": true,
  "roles": {
    "consultant": {
      "main": [
        "consultant",
        "u25-consultant",
        "u25-main-consultant"
      ],
      "peer": [
        "consultant",
        "u25-consultant"
      ]
    }
  },
  "registration": {
    "minPostcodeSize": 3,
    "autoSelectAgency": true,
    "autoSelectPostcode": true,
    "mandatoryFields": {
      "age": false,
      "state": false
    },
    "notes": {
      "agencySelection": "Lorem ipsum",
      "password": "Dolor sit amet"
    }
  },
  "urls": {
    "requiredAidMissingRedirectUrl": "https://www.domain.tld/requiredAidMissingRedirectPath",
    "registrationPostcodeFallbackUrl": "https://www.domain.tld/registrationPostcodeFallbackPath"
  },
  "requiredComponents": {
    "age": {
      "isEnabled": true,
      "options": [
        {
          "value": "50",
          "label": "20"
        },
        {
          "value": "51",
          "label": "21"
        },
        {
          "value": "52",
          "label": "22"
        },
        {
          "value": "53",
          "label": "23"
        },
        {
          "value": "54",
          "label": "24"
        },
        {
          "value": "55",
          "label": "25"
        },
        {
          "value": "56",
          "label": "26"
        }
      ]
    },
    "state": {
      "isEnabled": true
    }
  }
}

=== virtualidentityag/caritas-rework-onlineBeratung-consultingTypeService/src/test/resources/consulting-type-settings/null-value-consulting-type-settings.json
{
  "id": 1000,
  "tenantId": null,
  "slug": "null-values",
  "excludeNonMainConsultantsFromTeamSessions": false,
  "consultantBoundedToConsultingType": false,
  "welcomeMessage": {
    "sendWelcomeMessage": false,
    "welcomeMessageText": null
  },
  "sendFurtherStepsMessage": true,
  "showAskerProfile": true,
  "isVideoCallAllowed": true,
  "isSubsequentRegistrationAllowed": true,
  "sessionDataInitializing": {
    "addictiveDrugs": true,
    "age": true,
    "gender": true,
    "relation": true,
    "state": false
  },
  "whiteSpot": {
    "whiteSpotAgencyAssigned": false,
    "whiteSpotAgencyId": null
  },
  "groupChat": {
    "isGroupChat": false,
    "groupChatRules": null
  },
  "languageFormal": true,
  "roles": {
    "consultant": {
      "default": ["consultant"]
    }
  },
  "notifications": {
    "teamSessions": {
      "newMessage": {
        "allTeamConsultants": true
      }
    }
  },
  "registration": {
    "minPostcodeSize": 5,
    "autoSelectAgency": false,
    "autoSelectPostcode": false,
    "mandatoryFields": {
      "age": false,
      "state": false
    },
    "notes": {
      "agencySelection": null,
      "password": null
    }
  },
  "urls": {
    "requiredAidMissingRedirectUrl": null,
    "registrationPostcodeFallbackUrl": null
  },
  "requiredComponents": null
}
